// src/constants/index.js
export const LEVEL_MULTIPLIER = 0.1;
export const UPGRADE_COST_MULTIPLIER = 1.1;
export const MILESTONE_LEVELS = [25, 50, 100];
export const buildingNames = [
  "Neon Kiosk",
"Neon Cafe",
"Neon Arcade",
"Neon Diner",
"Glowing Laundromat",
"Neon Boutique",
"Luminous Bookstore",
"Neon Theater",
"Glowing Art Gallery",
"Neon Tech Hub",
"Luminous Hotel",
"Neon Skating Rink",
"Glowing Gym",
"Neon Marketplace",
"Luminous Condominium",
"Neon Music Club",
"Glowing Aquarium",
"Neon Corporate Tower",
"Luminous Park",
"Neon Harbor",
"Luminous Hospital",
"Neon University",
"Glowing Stadium",
"Neon Transport Hub",
"Neon Tower"
];
export const managerNames = [ "Kara the Kiosk Keeper",
"Cafe Commander Chris",
"Arcade Ace Amy",
"Diner Director Dylan",
"Laundromat Luminary Lily",
"Boutique Boss Bella",
"Bookstore Baron Ben",
"Theater Tycoon Terry",
"Gallery Guru Grace",
"Tech Titan Tim",
"Hotel Honcho Harry",
"Skating Specialist Sarah",
"Gym Giant Gina",
"Marketplace Master Max",
"Condominium Captain Claire",
"Music Maestro Mason",
"Aquarium Admiral Alice",
"Corporate Chief Casey",
"Park Protector Pete",
"Harbor Heroine Hannah",
"Hospital Head Heather",
"University Usher Uriel",
"Stadium Star Stanley",
"Transport Titan Tessa",
"Tower Topper Toby"
];